### PR TITLE
Update build-kdenlive.sh

### PR DESCRIPTION
**Pull request by carlosnewmusic**
Updating programs https://bitbucket.org/eigen/eigen git://code.dyne.org/frei0r.git and lame

### CODE REVIEW

**Comment by bmatherly** [comment]
General comments:
We moved away from code.dyne.org because it was unreliable. Has the reliability improved?

Also, I don't care for leaving the old entries commented out. That's the whole reason for Git.

I'll let Dan chime in on the specific versions - I don't have any problem with them myself.

**Comment by ddennedy** [comment]
Someone from Kdenlive should approve changes to this script from now on, but if I do not hear from them in a while, I will approve this minor change.
I completely agree to remove the commented lines.
Regarding frei0r repo, the one to use now is https://github.com/dyne/frei0r
We should do that for all the scripts. My repo was a stop-gap for a good while, but I am deprecating it. Dyne is authoritative, and GitHub provides better reliability - win/win.

**Comment by vpinon** [comment]
Hello,
Of course no problem for me...
Thanks a lot!

**Comment by carlosnewmusic** [comment]
already put in all

**Comment by ddennedy** [comment]
I applied your changes manually.

**Pull request closed without merging**
